### ISSUE TITLE
CLI fit for a Framework

### ISSUE THREAD

**Issue by VincentRPS** [Pycord-Development/pycord-v3#151]
**This is something still under consideration, and a wide variety of things will have to be asserted,
generalized, and decided before any work or other such may be put into a PR for this.**

The goal of v3 is to excel the reach of developers and allow them to reach higher goals. faster.

As with that, we will not only be giving a return to v2's CLI but expanding it and enhancing it to a degree
never seen with Discord libraries before.

The CLI will expand Pycord from a library, to a **framework** for Discord bots.

This will be sectioning into commands, and some points may not be as detailed as to be fleshed out later.

# `pycord`

The base command.

Returns the normal banner without bot information (unless inside a bot dir.)

## `pycord new`

Create a new bot for the framework.

This will form something like the following:

```
.env - Environment Configuration
pycord.toml - Configuration
bot.py - Main bot file
gears/ - Gears which are automagically loaded
   ...
lib/ - Bot library sectioning for v3. Used for things like Components
   ...
```

### Configuration

```toml
# all shown here are defaults

# allows deprecation and new versions of the config file without breaking developers' config.
edition = "2023.0.0"

[bot]
# bot.py's bot variable
bot_var = "bot"
# the directory for gears to reside in
gears_dir = "gears"
# load environment variables before startup
load_env = true
# the name of the token's environment variable
token_name = "TOKEN"

[cluster]
# whether clustering is disabled or not
enabled = false
# 0 means just use the amount of shards
total = 0
clusters = 1

[dev]
# whether to cluster in dev mode or not
cluster = false
```

## `pycord start` / `pycord run`

Starts the bot permanently either using `.run`, or `.cluster`.

**NOTE:** would not resync files on changes.

## `pycord dev`

Starts the bot in a development mode.
In this mode, files are watched and on any change the bot restarts *that specific **Gear**.*
